#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Write the Spark GB10 version into vllm/_version.py and package metadata."""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path

_VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)\+dsv4\.spark\.(\d+)$")


def parse_spark_version(version: str) -> tuple[int, int, int, str]:
    match = _VERSION_RE.fullmatch(version.strip())
    if not match:
        raise ValueError(
            f"version must look like 0.28.0+dsv4.spark.1, got: {version!r}"
        )
    major, minor, patch, release = match.groups()
    return int(major), int(minor), int(patch), f"dsv4.spark.{release}"


def version_py_text(version: str) -> str:
    major, minor, patch, local = parse_spark_version(version)
    return (
        "# SPDX-License-Identifier: Apache-2.0\n"
        "# generated by docker/gb10/stamp-version.py — do not edit\n"
        f"__version__ = version = {version!r}\n"
        f"__version_tuple__ = version_tuple = "
        f"({major}, {minor}, {patch}, {local!r})\n"
    )


def stamp_version_py(root: Path, version: str) -> Path:
    dest = root / "vllm" / "_version.py"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(version_py_text(version))
    return dest


def _rewrite_metadata(text: str, version: str) -> str:
    if re.search(r"^Version:\s*.+$", text, flags=re.M):
        return re.sub(
            r"^Version:\s*.+$",
            f"Version: {version}",
            text,
            count=1,
            flags=re.M,
        )
    if text and not text.endswith("\n"):
        text += "\n"
    return text + f"Version: {version}\n"


def stamp_dist_info(version: str, extra_roots: list[Path]) -> list[Path]:
    written: list[Path] = []
    roots = list(extra_roots)
    try:
        import site

        roots.extend(Path(p) for p in site.getsitepackages() if p)
    except Exception:
        pass
    seen: set[str] = set()
    for root in roots:
        if not root.is_dir():
            continue
        for meta in root.glob("vllm-*.dist-info/METADATA"):
            key = str(meta.resolve())
            if key in seen:
                continue
            seen.add(key)
            meta.write_text(_rewrite_metadata(meta.read_text(), version))
            written.append(meta)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "version",
        help="PEP 440 Spark version, e.g. 0.28.0+dsv4.spark.1",
    )
    parser.add_argument(
        "--root",
        default=os.environ.get("VLLM_ROOT", "/opt/vllm"),
        help="vLLM source root that contains vllm/",
    )
    args = parser.parse_args(argv)
    parse_spark_version(args.version)
    root = Path(args.root)
    dest = stamp_version_py(root, args.version)
    metas = stamp_dist_info(args.version, [root, Path("/opt/venv")])
    print(f"stamped {dest} -> {args.version}", flush=True)
    for meta in metas:
        print(f"stamped {meta} -> {args.version}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
